/*
 * lbsgw
 */
package com.app.lbs.common;

public class CommonConsts
{
  public static final String K_P_ERROR_CODE = "key-pass-error-code";
  public static final String TMN_CFG = "config_key";
  public static final String TMN_CFG_SOFTVERSION = "SOFTVERSION";
  public static final String TMN_CFG_GSM = "GSM";
  public static final String TMN_CFG_GPS = "GPS";
  public static final String TMN_CFG_VBAT = "VBAT";
  public static final String TMN_CFG_VIN = "VIN";
  public static final String TMN_CFG_LOGIN = "LOGIN";
  public static final String TMN_CFG_IMSI = "IMSI";
  public static final String TMN_CFG_IMEI = "IMEI";
  public static final String TMN_CFG_PSW = "PSW";
  public static final String TMN_CFG_DOMAIN = "DOMAIN";
  public static final String TMN_CFG_FREQ = "FREQ";
  public static final String TMN_CFG_TRACE = "TRACE";
  public static final String TMN_CFG_PULSE = "PULSE";
  public static final String TMN_CFG_PHONE = "PHONE";
  public static final String TMN_CFG_USER = "USER";
  public static final String TMN_CFG_RADIUS = "RADIUS";
  public static final String TMN_CFG_VIB = "VIB";
  public static final String TMN_CFG_VIBL = "VIBL";
  public static final String TMN_CFG_POF = "POF";
  public static final String TMN_CFG_LBV = "LBV";
  public static final String TMN_CFG_SLEEP = "SLEEP";
  public static final String TMN_CFG_VIBGPS = "VIBGPS";
  public static final String TMN_CFG_SPEED = "SPEED";
  public static final String TMN_CFG_CALLLOCK = "CALLLOCK";
  public static final String TMN_CFG_CALLDISP = "CALLDISP";
  public static final String TMN_CFG_VIBCALL = "VIBCALL";
  public static final String TMN_CFG_SMS = "SMS";
  public static final String TMN_CFG_VIBCHK = "VIBCHK";
  public static final String TMN_CFG_POFT = "POFT";
  public static final String TMN_CFG_WAKEUP = "WAKEUP";
  public static final String TMN_CFG_WAKEUPT = "WAKEUPT";
  public static final String TMN_CFG_SLEEPT = "SLEEPT";
  public static final String TMN_CFG_ACCLT = "ACCLT";
  public static final String TMN_CFG_ACCLOCK = "ACCLOCK";
  public static final String TMN_CFG_ALARM_LOGINF = "ALARM_LOGINF";
  public static final String TMN_CFG_ALARM_MEOFF = "ALARM_MEOFF";
  public static final String TMN_CFG_ALARM_LOWBTT = "ALARM_LOWBTT";
  public static final String TMN_CFG_ALARM_OOB = "ALARM_OOB";
  public static final String TMN_CFG_ALARM_SHOCK = "ALARM_SHOCK";
  public static final String TMN_CFG_PROTECTED = "PROTECTED";
  public static final String TMN_CFG_FILE0 = "FILE0";
  public static final String TMN_CFG_FILE1 = "FILE1";
  public static final String TMN_CFG_FILE2 = "FILE2";
  public static final String CMD_S2 = "S2";
  public static final String CMD_S10 = "S10";
  public static final String CMD_S11 = "S11";
  public static final String CMD_S12 = "S12";
  public static final String CMD_S13 = "S13";
  public static final String CMD_S14 = "S14";
  public static final String SMS_CMD_KQ = "KQ";
  public static final String SMS_CMD_GB = "GB";
  public static final String SMS_CMD_DW = "DW";
  public static final String SMS_CMD_GK = "GK";
  public static final String SMS_CMD_GG = "GG";
  public static final String SMS_CMD_BD = "BD";
  public static final String ACTTYPE_001 = "001";
  public static final String ACTTYPE_002 = "002";
  public static final String ACTTYPE_003 = "003";
  public static final String ACTTYPE_004 = "004";
  public static final String ACTTYPE_GET_SEQ = "005";
  public static final String CHECK_ON = "on";
  public static final String NO_DATA = "无数据";
  public static final int LENGTH_OF_COMPANY_ORGID = 8;
  public static final int LENGTH_OF_GROUP_ORGID = 12;
  public static final String KEY_RESP_XMLDATA = "respXmlData";
  public static final String MOD_APP_COMMAND = "module-app-command";
  public static final String PROCESSOR_SEND_SMS = "send-sms-processor";
  public static final long THOUSAND = 1000L;
  public static final long SIXTY = 60L;
  public static final long HUNDRED = 100L;
  public static final String DEFAULT_COLOR = "FFFFFF,000000";
}
